[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "*"
[[redirects]]
    from = "/*"
    to = "https://www.calibur.cn/:splat"
    status = 200
    force = true
